design_docs/Helpers.md, helpers/pedigree_from_sample_metadata.py, requirements.txt, test/input/mock_pedigree.json, test/input/mock_sm_lookup.json, test/test_generate_pedigree.py
- This is a fresh version of #26 without the messy rebase
- helper script for generating family data from sample-metadata:
1. Pedigree
2. Pedigree in PLINK format
3. sample -> participant reverse lookup
Early version of this script (#1) made some incorrect assumptions about the relationship between participants and samples. This version allows for a 1 -> n relationship, and all possible variations will be present in the final PED file
Use of the de novo functionality in Hail required the generation of a Pedigree in PLINK format, so that has been added as an option. I've confirmed that Peddy also accepts PLINK and .ped files interchangeably, so .fam is the new default for this application.
The mapping back from samples to participants is required when formatting results for presentation …
=> Fresh branch with SM-API script

reanalysis/interpretation_runner.py, reanalysis/run_reanalysis.sh, reanalysis/utils.py, reanalysis/validate_categories.py
- fixes #32 
allow for a second Pedigree file to be provided - this second file is optional, and is for a singleton representation of the same callset. This changes the following behaviours:
- results processing module is called twice, once with each pedigree file
- final results are written to different paths, depending on the pedigree used to generate them: [ singleton | summary ]_results.[ html / json ]
- The VCF processing module still takes only one Pedigree file. If that input file name contains 'singletons', the `de novo` category value is removed as each variant is read. That, in combination with the singleton structure in the pedigree means that analysis is done as a cohort of individuals, instead of families.
=> Run as singletons

.pylintrc, reanalysis/comparison.py, reanalysis/comparison_wrapper.py, reanalysis/hail_filter_and_label.py, reanalysis/html_builder.py, reanalysis/moi_tests.py, reanalysis/query_panelapp.py, requirements-dev.txt, requirements.txt, test/conftest.py, test/test_aip_comparison.py, test/test_hail_broad_filters.py, test/test_hail_categories.py
- contributes to #19
- splits a number of the methods on `main` to be more modular, i.e. the 'good quality variant' test monitored both `alleles` and `FILTERS` - this is now split into two methods, and the changes are cascaded accordingly
- The preceding branch contained testing up until the point where we had found variants of interest which were in the MT, and had not proceeded to the VCF (i.e. were called but not categorised)
- Here we take each of those variants, and procedurally investigate why they were not assigned categories
1. First isolate the variant of interest in the MT (throw an error if we obtain != 1 row)
2. Prepare the variant in the same way we pre-process in the main workflow (move variants to new locations in the MT, split each gene onto separate rows, filter assigned …
=> AIP part 7 - adds quality & category validation tests

reanalysis/interpretation_runner.py, reanalysis/utils.py, test/test_utils.py
- closes #56 
- adds a CLI flag to signal annotation skipping
- creates an enumeration to specifically identify different file types
- changes the `is this a VCF` test to `what file type is this`
- tests if an input is MT - if True, and annotation skipping flag is passed, the expected path of the annotated MT will be overwritten with the current input MT path
- this will be read during the category assignment phase
=> allow annotation skipping (+ tests)

reanalysis/hail_filter_and_label.py, reanalysis/interpretation_runner.py, reanalysis/moi_tests.py, setup.py, test/conftest.py, test/input/cpg_runtime_config.json, test/input/cpg_runtime_config.toml
- N/A
After @lgruen 's feature presentation, I re-implemented checkpoints in the hail query script, to segregate & resolve blocks of filter queries [details on slack](https://centrepopgen.slack.com/archives/C018KFBCR1C/p1656035482419579?thread_ts=1656031499.504459&cid=C018KFBCR1C). Runtime of the exact same operation was improved by ~40%.
- implements checkpointing in the Hail process:
1. Checkpoint after a batch of independent filters
2. Never run `count_rows()` prior to checkpoint
3. flip-flop the checkpoint write-path, so we can use multiple checkpoints without trying to write to the current read-path. Method used rotates the temp path extension `.mt` <-> `.mt2`
4. follow checkpoints with re-partitions (no way to auto-repartition AFAIK, despite checkpoint implementing a read & write)
- …
=> Implement Checkpoints

.gitignore, cohort_prep.sh, helpers/pedigree_from_sample_metadata.py, reanalysis/hail_filter_and_label.py
- fixes #59 
- based on initial testing, AIP is frequently missing de novo variants
- running in a notebook has shown that at least 4 clear de novo calls are being flagged as 'Low Confidence' by the in-built Hail implementation of https://github.com/ksamocha/de_novo_scripts
- Fix for now is to do no post-filtering of these calls
- Consider feeding this back to the Hail team...
Includes a new script to handle the generation of cohort pedigrees. This is just a convenience script, happy to remove it
When the pedigree generation script runs, I've shuffled the method ordering. This is so that the script outputs nothing unless all data requirements are satisfied (currently able to export the lookup JSON even if the pedigree generation fails)
=> Remove filtering of de novo by binned quality from main process

reanalysis/hail_filter_and_label.py, reanalysis/interpretation_runner.py, reanalysis/reanalysis_conf.json, reanalysis/utils.py, requirements.txt, setup.py
- partially resolves #72 
Various changes to reduce hard-coded dependence on CPG infrastructure
- we no longer assume the `bucket`, `bucket-tmp`, `bucket-web` structure. Instead, those suffixes are read from the config file and can be missing/empty strings, in which case the results will all be lumped into the same bucket
- added the `web_suffix` and `tmp_suffix` keys to the config template
- new method to read config and check for a 'good' (len > 0) string - if not returns None
- no changes to the annotation component
Squashed some argparse/click descriptions to squash down the line count
=> Platform independence changes

reanalysis/hail_filter_and_label.py, reanalysis/html_builder.py, reanalysis/interpretation_runner.py, reanalysis/moi_tests.py, reanalysis/utils.py, requirements.txt
- closes #76
- Compound hets just aren't heritable from one parent, so alter the logic
- The Comp-Het test now only checks parents and rules out as plausibly causative if either parent is affected, or if one parent has both variants
I was using a couple of methods to check that values exist in the config file... `dictionary.get(key)` works well enough that those methods are useless, so I've cut them out
=> Compound het check

reanalysis/hail_filter_and_label.py, reanalysis/html_builder.py, reanalysis/moi_tests.py, reanalysis/utils.py, test/test_moi_tests.py
- closes #77 
- removes the filtering out of variant ratio (AB) test failures
- instead these variants are flagged, with the flag presenting on the final report
- makes a spot in the ReportedVariant model for other flags we might want to add (e.g. partial penetrance, incidentalome)
Slight logical tweak to fix the comp-het test (was removing all C-H variants)
=> Remove ab filter, replace with flagging

reanalysis/moi_tests.py
- #84
- When running the comp-het check, don't assume that the mother/father of the current sample will be populated
- Note: This branch was used to run the Mito cohort
=> Skip absent parents during comp-het

reanalysis/html_builder.py
- N/A
- The script should allow for the internal:external ID mapping to be provided & used independently of the Seqr content
- Previous line either used both, or defaulted to showing only CPG### ID
=> translate sample ID even if not using seqr

reanalysis/hail_filter_and_label.py, reanalysis/utils.py, test/test_hail_categories.py, test/test_moi_tests.py
- Closes #90 
- No longer calls the naive de novo logic when generating Category4 - this means there's no need for 4 and 4b
- Investigation to follow on whether the need for this sub-category in the first place was the result of a fixable bug in Hail's implementation
=> Remove second de novo

design_docs/Annotation.md, design_docs/MOI_Checks.md, design_docs/PanelApp_interaction.md, helpers/get_untagged_incidental_genes.py, reanalysis/get_untagged_incidental_genes.py, reanalysis/hail_filter_and_label.py, reanalysis/html_builder.py, reanalysis/interpretation_runner.py, reanalysis/query_panelapp.py, reanalysis/utils.py, reanalysis/validate_categories.py, test/input/incidentalome.json, test/input/panel_changes_expected.json, test/input/panel_green_latest_expected.json, test/test_panelapp.py, test/test_utils.py
- closes #46
- closes #93
- when the analysis is triggered some runtime details are recorded in a JSON file and written to the output folder (file used as input, whether it was a MT converted to VCF, whether annotation was re-run, panelapp file used...). Pedigree file(s) are also copied to the output directory
- A lot of work around making the custom objects comparable (__eq__ and __lt__ methods) so that we can sort coordinates, AbstractVariants and Report objects
- Removes a layer of indexing in the output dict which is no longer required (due to variants being directly comparable)
- additional argument(s) are forwarded to the panelapp query to combine more other panels with the standard mendeliome data (relevant docs to be updated)
- if the additional panel contains a non-mendeliome …
=> allow for multiple panels in query

comparison/README.md, comparison/comparison.py, comparison/comparison_wrapper.py, comparison/run_comparison.sh, reanalysis/moi_tests.py, reanalysis/validate_categories.py, requirements.txt, setup.py, test/conftest.py, test/input/aip_output_example.json, test/test_aip_comparison.py
- closes #71
- results are saved into output files, rather than only printing to the Hail logs
- requires fewer defined inputs - works input paths out by using the run folder root location
- produces comparison stats for the # of matched and missed Seqr Training Flags
[This Hail Run](https://batch.hail.populationgenomics.org.au/batches/140982/jobs/1)
=> Comparison update

reanalysis/annotation.py, reanalysis/hail_filter_and_label.py, reanalysis/interpretation_runner.py, reanalysis/mt_to_vcf.py
- closes #58
This PR contains a collection of fixes across a couple of different categories
- In lots of places there is a non-functional change of `matrix` -> `mt`, to harmonise with the canonical use of mt as a variable name in the hail code base
- The step MT -> VCF prior to annotation takes AGES, and most of the variants will be filtered out downstream. To reduce overall time and expense for the end2end workflow, sites are removed from the MT where a QC failure filter is shown, and sites are removed if no present samples have alt alleles (possible hangover when extracting the cohort group from a X-cohort joint call). This can be altered to behave differently if required, but for AIP-specific use the filter failures are removed anyway; not doing this removal up front just creates …
=> Field audit + tweaks

reanalysis/vep/jobs.py
The VEP data location on the `cpg-reference` bucket is parameterised by version now, so needed a slight adjustment to remove the hardcoded `/vep/GRCh38` path.
=> VEP: slight change in setting up mount

helpers/cohort_prep.sh, helpers/file_prep.sh, helpers/pedigree_from_sample_metadata.py, reanalysis/hail_filter_and_label.py, reanalysis/html_builder.py, reanalysis/interpretation_runner.py, reanalysis/query_panelapp.py, reanalysis/validate_categories.py, test/input/panel_changes_expected.json, test/input/panel_green_latest_expected.json, test/test_panelapp.py, test/test_validate_methods.py
- closes #105
A couple of QoL changes to helper scripts, useful when setting up new cohorts to run through AIP
- copies all the 'boilerplate' files from the acute-care bucket to the target bucket (CSQ string header line, VQSR header line, pre-panelapp mendeliome gene list)
- when parsing the pedigree and internal:external ID mapping from metamist, includes a `--copy` argument to additionally push those files directly from local to GCP (saves 2 manual copying operations, will fail if local user doesn't have write permission/is not auth'd)
- does a better job of logging the names and versions of all panels parsed as part of the analysis (name/version/id) in the panelapp output
- counts all family structures common between the VCF and pedigree, and writes into the results metadata
- counts …
=> Update report meta

reanalysis/hail_filter_and_label.py, reanalysis/interpretation_runner.py, reanalysis/mt_to_vcf.py, reanalysis/reanalysis_conf.json
- Closes #113 
- instead of having 2 one-line files complicating setup of new datasets, hard-code the contents and write at runtime
- CSQ being hard-coded makes more sense anyway, as the CSQ content/ordering is defined in-code
=> Remove two tiny files, hard-code content

release_scripts/csiro_release.sh
- https://github.com/populationgenomics/seqr-private/issues/11
- adds a bash script to copy relevant CSIRO data to a release bucket
=> adds script to copy csiro data to release bucket

reanalysis/hail_filter_and_label.py, test/test_aip_comparison.py, test/test_hail_broad_filters.py
- closes #123 
- Shifts logic to using the AC, AF, AN in `mt.X` instead of `mt.info.X`
=> check the AC/AF/AN attributes at the top level, instead of in info

reanalysis/hail_filter_and_label.py
- relevant to #123
- I left some incorrect syntax in the previous PR
- for top level attributes, you need to check either `row_key` or `row_value` when checking if an annotation exists
- for any further nested level it's fine to check `if X in mt.info`
-  [x] Linting checks pass
=> correction to syntax

reanalysis/hail_filter_and_label.py
- #123, again
- the conditional check was returning True if no problems were found
- that is 100% wrong - True is success, i.e. no `problems` with the annotations
There are no explicit tests of this method, as it's quite verbose to write. I'm going to make an issue to unit test this method, as that would have saved 2 PRs today
=> conditional failing despite checks succeeding

reanalysis/interpretation_runner.py, reanalysis/reanalysis_global.toml
- closes #137 
- Writes human-useful files to the `-analysis` subset bucket instead of directly in main
- This fragments the output across more folders, but makes it user-accessible as/when required, e.g. debugging
- Summary JSON, Pedigree(s), and PanelApp data
- Takes the analysis suffix from config, where it can be missing/None (i.e. if the deployment doesn't have a separate analysis bucket, results will be written to the regular location)
=> Write human results in analysis

reanalysis/html_builder.py
- N/A
- code no longer fails when cohort Seqr config is missing
- makes it a little easier to run non-seqr cohorts (e.g. validation/1000g)
=> permit missing seqr config

reanalysis/hail_filter_and_label.py, reanalysis/html_builder.py, reanalysis/interpretation_runner.py, reanalysis/reanalysis_global.toml, reanalysis/utils.py, reanalysis/validate_categories.py, test/test_html_builder.py
- closes #156
- This is not a FIX per se, but is a housekeeping change to reduce the output JSON size by about 80%, and reduce logic required to interpret the JSON downstream.
- The JSON dump is a huge file with low info density
- The full collection of transcript consequences is currently stored, but much of this content is repetitive (e.g. storing the hgvsp `e.g. "ENSP00000329880.8:p.Met1?"`, alongside Protein ID, residue number, AA change, swissprot, trembl...). Reducing this to a minimal set of values will shrink all files downstream with no real loss of information.
- The AB ratios of every sample are stored against every variant - majority of these are `0.0`, and serve no purpose after the report objects are generated. These alone make up ~half the lines in each output JSON
- Each …
=> Clean up output json

reanalysis/interpretation_runner.py, reanalysis/moi_tests.py, reanalysis/reanalysis_global.toml, reanalysis/utils.py, reanalysis/validate_categories.py, test/test_results_comparison.py, test/test_validate_methods.py
- closes #155 
- enables #154
@cassimons in particular, can you check that this implementation feels fit for purpose?
- This is a pretty THICC change, with 2 Cs
- Introduces the concept of filtering current results by removing previously seen results
- Admittedly this all needs documenting, but the docs need a user-focused overhaul anyway so this will be done at that time
1. The config can now contain the key `dataset_specific.historic_results` - this will be the path to a cloud folder containing cumulative results files - this would be a candidate use of metamist's `analysis` objects if we wanted to tie AIP to CPG.
2. When AIP runs, the results will be cleaned against these prior results:
a. The latest file in the `historic_results` folder will be identified using the `stat().st_mtime` …
=> Filter to new results

reanalysis/moi_tests.py, test/test_moi_tests.py
- N/A
- See https://centrepopgen.slack.com/archives/C035QN8C0DN/p1669938940053829?thread_ts=1669856845.568669&cid=C035QN8C0DN
- Now that the thresholds for HOM/HEMI in reference databases are much lower (since #151), the conditionals which were previously 'greater or equal' are now invalid
- e.g. 'remove this variant if the number of GnomAD HOMS **>=** threshold' doesn't make sense if the threshold is 0
- Move all threshold AF/AC tests to exclusively use greater than during MOI tests
=> For thresholds, permit exact match

reanalysis/html_builder.py, reanalysis/interpretation_runner.py, reanalysis/moi_tests.py, reanalysis/utils.py, reanalysis/validate_categories.py, test/test_moi_tests.py
- N/A
A couple of tweaks
- Grabbing a 'minimised variant' representation is done much earlier on in the reporting stage, instead of leaving all the cleaning steps until the last minute
- the first time we write the 'cumulative data' file, include the dates of all variants
=> Copy variant each time

reanalysis/interpretation_runner.py, reanalysis/reanalysis_global.toml
We switched to generating config [by merging templates in AR](https://github.com/populationgenomics/analysis-runner/pull/559), with templates generated by Pulumi in [cpg-infra](https://github.com/populationgenomics/cpg-infrastructure/pull/20) as well as by the CI in corresponding [images](https://github.com/populationgenomics/images/pull/56/files) and [references](https://github.com/populationgenomics/references/pull/2) repositories. When running outside of our infra, absolute paths are expected now, so modifying AIP configs accordingly.
=> `reference_path` and `image_path` now expect absolute path in configs

reanalysis/interpretation_runner.py, reanalysis/reanalysis_global.toml
The problem: VEP jobs expect a site-only VCF, and would run out of disk when used with a full VCF with genotypes. 
Adding a job to strip off genotypes.
Depends on https://github.com/populationgenomics/production-pipelines/pull/227
=> Make site-only VCF before passing to VEP

clinvar/conflict_huntr.py
- Closes #174
- The initial version of the Clinvar summarising script created all the ~800k entries as a single JSON, converted that to a DataFrame, then to a HailTable. Somehow, converting 200MB of JSON into a Hail Table consumed 80GB+ of memory, and required a massive resource allocation
- Switching this to syntax already in use by @vladsavelyev (modelled on the original pipeline from Broad?), the data is written & ingested line-by-line on a fixed schema basis ([See code here](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/query_modules/vep.py))
- This whole process now takes 3 mins, a trivial resource allocation, and is light enough that it could be run with each AIP run (i.e. pull down the latest clinvar data at runtime, and regenerate annotations …
=> redraft clinvar write

reanalysis/templates/macros.jinja
Adds a pedigree icon macro for use in jinja.
Usage: {{ macros.ped_symbol(sex='1', affected='2') }}
or {{ macros.ped_symbol(sex='female', affected='false') }}
=> Add ped icon macro

reanalysis/interpretation_runner.py, reanalysis/moi_tests.py, reanalysis/validate_categories.py, test/test_moi_tests.py
- N/A
- there was a genotype display bug where both Het and Hom would display as `Het` - a silly conditional copy/paste error
- unrelated to, but found because of that error there is also an MOI issue:
1. PanelApp has a whole range of MOI options, including niche variations like `X-LINKED: hemizygous mutation in males, monoallelic mutations in females may cause disease (may be less severe, later onset than males)`. I'm parsing these options into small Monoallelic/Biallelic/mono_and_biallelic instead of implementing an MOI test 1:1. For this example I'm reducing this to `X-linked Monoallelic` based on a conditional check flow.
2. Initially the PanelApp query JSON contained the full strings, and they were reduced later on to the 'simple' representation
3. Recently I moved the simplification …
=> Fix genotype bug

.github/workflows/docker.yaml, .github/workflows/test_docker.yaml
- parametrises the test tag (which should allow the arg to be overwritten)
- removed the github SHA from the image name - @illusional mentioned this on a prior PR, but I hadn't realised how massive that name was until the images started being pushed
=> tag using version, not SHA. Parametrise test tag

reanalysis/html_builder.py
- HTML generation crashes when not all samples are present in the Seqr lookup. This is a patch fix, and would go away if we have an operational Seqr API to retrieve this data instead
- When looking up the Seqr-ID for a participant, don't crash and burn if the sample ID is not in the Seqr lookup
- I ran into this situation when there was a new joint call, and the seqr lookup file had not been updated to reflect the new samples. This could also happen if a cohort was run through AIP prior to being loaded into Seqr
- Basically it shouldn't happen often/ever, but it shouldn't fatally fail - it will be clear in the report HTML which samples don't have links to Seqr, and this can be updated as required
=> don't fail if the sample is absent from the seqr lookup

reanalysis/interpretation_runner.py
- Corrects spacing in the `wget && wget`, spotted by @illusional
=> corrected command spacing

reanalysis/templates/index.html.jinja, reanalysis/validate_categories.py, test/conftest.py, test/test_aip_comparison.py, test/test_validate_methods.py
- Closes #196 
- removes reliance on the Peddy.summary function, which can't account for samples in the Pedigree but missing from the joint-call
- inserts additional test for Trio, trio with missing participant, and quad structure
- typo in report
=> re-works the family size counter

reanalysis/templates/index.html.jinja, reanalysis/templates/variant_table.html.jinja
Fixes variant grouping that was broken by having a dash in a extID. It looks like this still can result in some odd line wrapping in IDs, but we can figure that our another time.
=> fix grouping by individual

.github/workflows/test_docker.yaml, reanalysis/interpretation_runner.py
- The `make-vcf-subsets` job(s) were not dependent on the prior job completing
- sets a new workflow dependency during graph creation
- not sure how this didn't fail previously... A Xmas Miracle
=> corrected workflow graph

.github/workflows/test_docker.yaml
- completely biffed on how to get the input variable into the actual tag when designing the test workflow
- I think it's still important to permit multiple separate in-development branch images to be built, so I'm avoiding hard-coding 'test' as the tag
- moved to the corrected (?) syntax, modelled on [this](https://github.com/populationgenomics/analysis-runner/blob/main/.github/workflows/deploy_server.yaml)
=> test tag fix

.github/workflows/test_docker.yaml, reanalysis/hail_audit.py, reanalysis/hail_filter_and_label.py, reanalysis/utils.py, test/test_aip_comparison.py, test/test_hail_broad_filters.py
- Closes #214
- Clinvar known pathogenic variants are removed from the dataset if they are over 1% within the cohort
- Disables both joint-call and population AF filters where a variant is known pathogenic
- We already defer to Clinvar ratings over population frequencies, this extends that to the within-cohort joint-call frequency
- The specific variant that started this was [this one](https://seqr.populationgenomics.org.au/project/R0021_mito_disease/saved_variants/variant/SV0000659_1545069018_f000316_a), which is now found using an image built from this branch [here.html](https://test-web.populationgenomics.org.au/mito-disease/reanalysis/chr15_2023-01-24/summary_output.html)
- scraps all annotations not required to run AIP prior to the first checkpoint. This is an effort to reduce the …
=> remove tons of unused MT data up front - shrink checkpoint times

.github/workflows/test_docker.yaml, reanalysis/html_builder.py, reanalysis/templates/variant_table.html.jinja, reanalysis/utils.py, test/test_results_comparison.py
- Closes #208
- Removes (completely) the 'subtract variant from analysis if previously seen' logic, replacing with 'assign `first_seen` date based on historic data'.
- Removes "YYYY-MM-DD_HH:MM:SS" format in favour of "YYYY-MM-DD" for the first_seen to display better in the report.
- Includes the first seen value in the report table (can filter/sort, but no date-range widget)
First_seen is probably the wrong name for this field. The value in here is the most recent date that one of the present categories was first seen. Worked example because otherwise I'll forget the reasoning:
* Fam A has Variant X (Cat. 1)
* A report is generated on Day D, so the 'cumulative data' file is extended to say that in Fam A Var X had a Cat. 1 variant on Day D
```
{
FamA:
VarX:
Cat1: D
}
```
* Later on Day N …
=> Tag with first time seen

reanalysis/utils.py, test/test_panelapp.py, test/test_utils.py
- N/A
- When moving to the match/case syntax, I inserted a preparation stage that stripped out all punctuation (i.e. to make sure that 'biallelic,' matched to 'biallelic'
- This also strips out the hyphen in `x-linked`, so none of the X chromosome MOIs were matching to any of the cases, which were unchanged as `x-linked` instead of `xlinked`
- This results in them falling through and hitting the default condition, which assigned `Hemi_Bi...` to all chrX genes
- The test case that would have caught this was also changed to expecting X_Biallelic, as we also changed the nominated default leniency at the same time, leaving no test case for X_Mono
=> correction of MOI parsing

reanalysis/hail_filter_and_label.py, reanalysis/moi_tests.py, test/test_aip_comparison.py, test/test_hail_broad_filters.py
- Permit FILTER flagged variants to pass through Hail stage, if registered as Pathogenic in Clinvar
- Escape clause in FILTER test
- updates relevant tests
- 'ronseal' isn't a very good docstring message, is it...
=> Clinvar passes filters

helpers/forbidden_gene_check.py, reanalysis/moi_tests.py, reanalysis/query_panelapp.py
- Fixes a regex bug - I was making a date string from minutes instead of Months
- Give this script a number of dates, optionally a pheno-matched panels JSON
- Gets the green genes in the current (latest) version of all those panels 
- for each date, find the latest version of each panel at that date, and get all the genes
- get current - (genes from that point in time), and save to a file
This facilitates using the 'forbidden_genes' blacklist feature to run a series of retrospective runs, simulating a panelapp point in time with each one (by blocking variants that have been added to panelapp since that time)
=> forbidden gene finder

release_scripts/broad_rgp_release.sh
- Script to release some data to MSFT/Broad
- This should probably be replaced with `gcloud storage`, but I'm not 100% sure of the argument order to use a specific order
- `gcloud storage -u broad-rgp copy -r ...`?
-
=> script for release copy

reanalysis/hail_filter_and_label.py, reanalysis/reanalysis_global.toml, reanalysis/validate_categories.py
- Hail stage breaks when no genes are new - Hail cannot impute the member types of an empty set so it just falls over
- If no genes are New, pass back None instead 
- During Cat. 2 annotation if new genes is None, just flat annotate 0 as the category value for all rows
Not an urgent fix
=> allow for no new genes in hail

reanalysis/interpretation_runner.py, requirements.txt, setup.py
- N/A
- following [this fix](https://github.com/populationgenomics/production-pipelines/pull/286), reverts to using the CPG-workflows library method
- removes need for a BCFtools image
https://batch.hail.populationgenomics.org.au/batches/421216 (cancelled after initial success)
=> Revert to GATK sitesonly VCF generation

reanalysis/clinvar_runner.py, reanalysis/summarise_clinvar_entries.py
- unless the default job image is set, the jobs run in a basic `ubuntu:20.0` image, which lacks wget
- run the child jobs in the driver image
=> Clinvar summary in driver image

helpers/report_hunter.py
- adds a shebang to prevent bash running a python script
- The alternative would be `"script": ["python3", "./report_hunter.py"]`?
=> add shebang to report finder script

reanalysis/query_panelapp.py, test/input/reanalysis_cohort.toml
- The current approach is to let forbidden genes linger in the analysis results until the HTML is generated, and remove them later. This approach doesn't work for the historic analysis where we want to artificially back-filter results using a gene list, as it means that genes will be blocked from Cat2 status (as they are already in the historic results), but they will then be removed. This creates a weird gap where it's tough to do a meaningful historic interval analysis.
- Remove genes from the panel data completely if they're blacklisted, so that when they stop being blacklisted (artificially representing the point in time where the gene was marked green on the relevant panel) they will populate properly as a new gene.
- This is a relatively minor change, but it's getting to the point …
=> removes forbidden genes in first pass

reanalysis/clinvar_by_codon.py, reanalysis/hail_filter_and_label.py, reanalysis/html_builder.py, reanalysis/reanalysis_global.toml, reanalysis/templates/variant_table.html.jinja, reanalysis/utils.py, test/test_hail_categories.py
- Implements a new category based on the PM5 ACMG criteria
- Closes #140
- Includes a helper script with code used to take a clinvar VCF annotated by VEP, reshuffle the content into a Hail Table linking all Protein_ID and residue number with all relevant clinvar alleles
- This helper isn't being built up into a proper wrapper script because once VEP is released on Hail Query that will be much easier to develop. Pretty manual until then
- Includes a `categorydetailspm5` which will collect all clinvar missense submissions at the same residue as a current missense
- any matched submissions that are an exact match to this current variant are removed
- This data is processed to create a new column in the report HTML with hyperlinks to the other entries (if appropriate)
- needs further testing, …
=> Annotate common tx csq

helpers/prepare_aip_cohort.py, reanalysis/interpretation_runner.py
- Closes #266 
- alters how singleton runs are operated; instead of pairing a 'regular' and a 'singleton' run at the same time, AIP can run in singleton mode, with appropriate output paths
- Helper method for setting up a run has the singleton mode reimplemented (this was removed a while back)
- The pairing of the singleton and regular versions was logical, based on being able to share workflow components (PanelApp, Hail), but falls down in the current situation where a family analysis was already run, and running singleton analysis would require that to be repeated
=> Mods for singleton runs

helpers/report_hunter.py, reanalysis/html_builder.py
- AutoClass migration is playing havoc with 'find latest files by edit date'
- The more robust process would be to log files in Metamist, retaining only one active file
- Contributes to solving #272
After completing the HTML generation process:
- query for all 'web' files in the same dataset
- find any which fit the same subtypes as the current analysis (genome/exome, familial/singleton)
- If any active files are found, mark them as inactive (@illusional  I remember an issue where either querying for `active=True` didn't really limit the search, or updating active to inactive wasn't persisted. Is this still an issue?)
- Register the current output file
This change would be a predicate for shifting the report index generator to using metamist.
The downstream plan would be to find the most …
=> register html outputs in metamist

helpers/report_hunter.py, reanalysis/html_builder.py, reanalysis/interpretation_runner.py, reanalysis/validate_categories.py
- Report Index page is still rekt - all the latest content is collected accurately, but the output path (exact GCP path to the HTML file) is not suitable for access by analysts
- Until now the HTML script only received the full GCP path to write results to, so obtaining the proxied path would need to be reverse engineered - avoid this behaviour
- The Report path (`gs://`) and proxied access path (`https://main-web.BUCKET.FILE`) are not the same - for the index page we need the latter
- Instead of passing the fully-resolved output paths to the result generation and HTML generation scripts, just pass the file name
- When the file paths are due to be used for writing data, generate the full paths
- This means we preserve the ability to join the `web_url` prefix, the `output_prefix`, and the …
=> write web proxy path into metamist

reanalysis/hail_filter_and_label.py, reanalysis/reanalysis_global.toml
- Closes #273
- This issue was identified by CSIRO collaborators digesting VCFs
- Originally we used a fixed CSQ string in the header, and stored all those components in the VCF
- The retained fields can be edited in config, but this has not been reflected in the header (i.e. the CSQ header description will contain all fields, even if they're not written into the variant line)
- This change means that the VCF header line will be composed explicitly based on the contents of the config file at runtime
The full CSQ header prior to this change:
```toml
[csq]
csq_string = [
'allele',
'consequence',
'symbol',
'gene',
'feature',
'mane_select',
'biotype',
'exon',
'hgvsc',
'hgvsp',
'cdna_position',
'cds_position',
'protein_position',
'amino_acids',
'codons',
'allele_num',
'variant_class',
'tsl', …
```
=> Link CSQ contents to the config file

reanalysis/validate_categories.py
Less invasive version of #290
- Closes #289 
- If we are assessing a Cat. 1 variant with any of the most permissive MOIs (Mono_And_Biallelic or Unknown, and the Allosomal equivalent Hemi_Mono_in_Female) we attach an additional flag if we find a Dominant MOI
- Currently this is `Lenient MOI Used`, but happy to hear suggestions
- The super lenient MOI(s) can be attached either because the Mendeliome/Base panel has that MOI, or as a result of multiple panels being used (Mono on one, Biallelic on another = Mono_And_Biallelic). This change will not differentiate between those two different situations. AFAIK the issue is the relationship between the ClinVar relaxed MOI testing and the lenient MOIs, so it doesn't really matter how we obtained that MOI.
- This will be applied even if both …
=> Flag Lenient Cat.1 Dominant

reanalysis/summarise_clinvar_entries.py
- Left a bug in, CRON job can't run for a cohort not specified in config (i.e. when it runs as `talos`)
- makes the cohort_config bit fully optional. If it runs with a dataset not present in config, no submissions will be excluded on a per-site basis
=> facilitate non-cohort running

.github/workflows/clinvar_runner.yaml, helpers/clinvar_conf.toml, reanalysis/reanalysis_global.toml
- makes sure that genomic-autopsy will be caught by the report hunter script
- adds GA with the fetal abnormalities panel
- amends the clinvar POST config so that the `get_cohort_config()` method won't fail
- updates the scatter count for ClinVar (splitting the genome into 5 resulted in ~4 hour VEP runtimes, 50 is pretty reasonable)
=> include genomic-autopsy in report runner

helpers/report_hunter.py, reanalysis/interpretation_runner.py, reanalysis/metamist_registration.py, reanalysis/query_panelapp.py, reanalysis/summarise_clinvar_entries.py
- A couple of the graphQL queries are not valid syntax, so the report-hunter script can't complete
- updates the `active:true` and `type:web` queries to be valid syntax
- changes the metamist reporter script so that only `.html` files are created as web analyses
=> various followup metamist changes

helpers/clinvar_conf.toml, helpers/report_hunter.py, reanalysis/reanalysis_global.toml, reanalysis/run_reanalysis.sh, reanalysis/summarise_clinvar_entries.py
- See [Slack Discussion here](https://centrepopgen.slack.com/archives/C035QN8C0DN/p1690529235514449?thread_ts=1688629602.505809&cid=C035QN8C0DN)
- Site filtering included a typo, so we were not correctly filtering out our own ClinVar submissions
- Report Hunter is still vulnerable to any `web` analysis entries which aren't HTML files
- Even new ClinVar entries can be un-dated, which will affect all date filtration we do
- If we run any date filtering, remove all un-dated entries from ClinVar (instead of allowing all undated entries to pass all date thresholds)
- Correct the site blacklisting, and publish to logs to clarify the exact sites being removed
- Correct Web Analysis entry parsing, allowing for soft failures
=> Updates to ClinVar parsing

.github/workflows/clinvar_runner.yaml, helpers/prepare_aip_cohort.py, reanalysis/clinvar_runner.py, reanalysis/summarise_clinvar_entries.py
- Pedigree generation broken by graphQL change: participants dropped off if only one parent was present
- ClinVar script doesn't handle no date being supplied
- Fixes the itertools.product() call when generating pedigree rows
- adds a default date to the clinvar output file
- when the CI workflow automatically generates ClinVar summary data, it excludes MCRI entries
=> Correction to clinvar no date supplied

reanalysis/html_builder.py, reanalysis/templates/index.html.jinja, reanalysis/validate_categories.py, test/input/reanalysis_cohort.toml, test/test_validate_methods.py
- Closes #316 
- Adds a `solved` param in config, specific to the dataset/project. This can be family IDs (any format) or individual IDs (CPGAAAA)
- Cases marked as solved are flagged as `solved: True` in the output JSON
- In the HTML generation step, these solved cases are removed from the presentation table, and added to the Statistics tab
- Solved cases are not recorded in the history file, so this can be easily reversed
=> Solved case source of truth from config

Dockerfile, helpers/report_hunter.py, reanalysis/templates/index.html.jinja, reanalysis/validate_categories.py, requirements.txt
- Builds on a driver image containing a version of hail without workflow generation issues
- Tweaks how samples/IDs are handled, so that we can correctly mark cases as solved on the basis of family ID or individual 
- Report fix (IDs in wrong div) 
- Report Hunter script (was appending date with each analysis entry, instead of finding only the latest for each time point)
=> Avoid broken hail version during build

helpers/report_hunter.py, reanalysis/html_builder.py, reanalysis/metamist_registration.py
- Production-pipelines now writes report/result entries as metamist analysis type 'aip-report' and 'aip-results'
- This change is not compatible withe current index builder script
- metamist analysis reporter now writes new entries using those analysis types
- report finder now detects those analysis types
- unrelated - seqr lookup dict can be empty/absent without causing failures
=> update to use new analysis types

.github/workflows/clinvar_runner.yaml, .github/workflows/docker.yaml, .github/workflows/index_page_builder.yaml, .github/workflows/lint.yaml, .github/workflows/test.yaml, .github/workflows/test_docker.yaml, helpers/report_hunter.py
- The index page (http://popgen.rocks/aip_index) was being published with invalid hyperlinks
- Reason - the string replacement of `gs://cpg-PROJECT-main-web` with `https://main-web.populationgenomics.org.au/PROJECT` was being done using the `default` project
- This script runs under the automated account ID `talos`, so the replacement was trying to string replace `gs://cpg-talos-main-web` each time, which was not present in any of the output strings
- Also tidies up the use of `logging`, so we're not barfing all the metamist results into the hail log every time
- corrects this so that each analysis object runs a string replacement based on the correct project
- updates all the CI action versions
=> Fix report hunter

reanalysis/hail_filter_and_label.py, reanalysis/interpretation_runner.py
- When multiple datasets are run concurrently in the pipeline, they are all checkpointing to the same tmp location in `cpg-seqr-main-tmp` due to this use of `output_path`
- This is the only use of output_path I can find (other than in `interpretation_runner.py`, which is a completely different entrypoint, unused by prod-pipes
- pass this specific dataset name into the hail labelling stage (optional, defaults to workflow.dataset)
- writes temp files and checkpoints to a dataset-specific path
=> Clarify dataset in in-module use of output_path

reanalysis/hail_filter_and_label.py, reanalysis/hpo_panel_match.py, reanalysis/html_builder.py, reanalysis/reanalysis_global.toml, reanalysis/templates/variant_table_child_row.html.jinja, reanalysis/utils.py, reanalysis/validate_categories.py, test/test_hail_categories.py
- AlphaMissense scores aren't recognised as a category
- Adds categoryboolean6 - binary classification based on AM's default thresholds
- Should be compatible with MTs where `vep.transcript_consequences.am_class` is absent
- Test added for am_class classification & missing AM scores
- Correction to Project label in metadata
- AM scores added to drop-down drawer (unless it's missing)
=> Added AlphaMissense Cat6 class

reanalysis/reanalysis_global.toml, requirements-dev.txt, requirements.txt
- Requests vulnerability was identified, patched version available
- updates a couple of package requirements
- bumps the standard job timeout (VEP was failing for some large fragments)
=> Dependabot instigated req. bump, timeout increase

reanalysis/hail_filter_and_label.py, reanalysis/hail_filter_sv.py, reanalysis/interpretation_runner.py
- "jvm jobs cannot be on lowmem machines" - this Hail filtering process is very lightweight, and can be run from a laptop, but there appears to be a hard restriction on machine type when running a Hail Query batch
- https://batch.hail.populationgenomics.org.au/batches/430115/jobs/3
- updates the `init_batch` call to use standard instead of lowmem machines
=> "jvm jobs cannot be on lowmem machines"

reanalysis/moi_tests.py, reanalysis/utils.py
- Failed to call an expected Comp-Het in a production run
- Both variants in the comp-het were assigned Support and Cat6 (and maybe a couple of other categories)
- I'm confused - this seems like quite a core bug that should have cropped up before, but the code here hasn't been touched in a year. It definitely appears to be a bug, and suggests we've been under-reporting Comp-Hets in various cohorts
In AIP variant representation there are 3 types of category which can be assigned to a variant:
- support
- boolean (applies to all samples)
- sample (applies to subset of samples, e.g. de novo)
When testing that 2 variants can form a Comp-Het, we screen out cases where both variants are only supporting. The logic in this test was:
```
if var1 is support ONLY and var2 is support ONLY: fail
``` …
=> Fix Comp-Het test

reanalysis/reanalysis_global.toml, reanalysis/utils.py, test/input/reanalysis_global.toml
- closes #349 
- In some situations we may want to run AIP with specific categories removed (e.g. because a label which provides value in trios may generate too much noise in singletons)
- Instead of tweaking parameters in config, this allows us to completely remove categories from consideration
- This removal is applied after the Hail/labelling stage, so that blocking/unblocking categories in config is reversible without having to re-run the labelling stage (longest, most expensive part)
=> Allow ignoring of specific categories via config

reanalysis/query_panelapp.py, reanalysis/utils.py
- A couple more changes relating to THE COHORT THAT MUST NOT BE NAMED
- That project's lack of a `-test` bucket means no prior data of any form, which has resulted in exercising a few config paths that weren't exposed before
- When running a (now vs. 12 months ago) assessment for new genes, correct the expected data type for the relevant model
- If there's no historic data location, don't try to save any (tries to open the GCP path `None/<file>`
=> Model correction

reanalysis/hpo_panel_match.py, test/test_metamist_hpo.py
- HPO terms in the reports are naked (HPO:NNNN only)
- Closes #356
- After matching HPO terms to relevant panels, they are enhanced by appending their plain text short description
- This will then be added in the final report, to make reading easier, removing the need to find a separate lookup
-
=> Improve HPO presentation in reports

reanalysis/hail_filter_and_label.py, requirements.txt, test/test_hail_categories.py
- Closes #353 - was caused by exomes and genomes writing to (and potentially resuming from) the same checkpoint path
- There may have been a bug in Cat. 4 (de novo) [here](https://github.com/populationgenomics/automated-interpretation-pipeline/blob/main/reanalysis/hail_filter_and_label.py#L511-L533)
- The intention of this logic is 
1. get all relevant consequences (VEP critical + missense)
2. filter transcripts to the ones which have those relevant consequence annotations
3. the final clause is supposed to be "filter variants to ones where there is either at least one transcript with a relevant consequence annotation, OR the variant has a substantial SpliceAI score"
4. the final clause instead filters for variants which have a consequential transcript annotation AND NO SpliceAI score
- …
=> Fix Cat 4 logic, reorganise methods

reanalysis/minimise_output_for_seqr.py, reanalysis/utils.py
- #366 
- Inter-chromosomal variants don't have a length. Instead, we set the 'SVLEN' to be 'chrX:12345' (the other side of the breakpoint)
=> Allow for interchromosomal split variants

Dockerfile, requirements.txt
- This attempts to build off a lighter docker image than the CPG driver
- Previous attempt at this used a global Hail dockerfile as a base image - that's not valid, as QoB within our infrastructure requires us to use a specific version of Hail which has been deployed within our infra
- The benefits from this optimisation are limited by the fact that within CPG infra we have to use a CPG-built version of Hail
- Pins the Hail hash to the version build from our hail fork
- uses a similar build plan to the driver image, minus a lot of irrelevant weight
=> Re-base image

reanalysis/html_builder.py
- This is the real reason for #354
- Since moving to a model where 2 reports are generated - one for all variants, and one for 'new variants today', we've occasionally hit an issue where we fail to reference a column within a dataframe. The reason: if no variants are found at all, the list of dictionaries passed to the DataFrame builder is an empty list, so the result has no columns. This typically happens when filtering to latest, but could potentially happen if no variants are found at all.
- If the list builder contains no data, gracefully exit
=> Allow for no categorised variants

reanalysis/hail_filter_and_label.py, reanalysis/validate_categories.py
- `show_default` is not a valid argument to argparse - CoPilot led me astray. Looks like `show_default` is a valid argument for the Lua version of the library, but not for Python, so this was causing startup failures.
- A while back I removed some checkpoints from the Hail process - the recent runtimes are WAY higher than I would expect, so reinstating some checkpoints to see if that alleviates the issue.
- Remove bad argument from argparse
- adds checkpoints back in to match a previous state ([here](https://github.com/populationgenomics/automated-interpretation-pipeline/blob/2fbb058d728bf12d82c6c4b14c7c118a64ab8dd4/reanalysis/hail_filter_and_label.py))
=> show_default fix

.github/workflows/docker.yaml
In a bid to introduce better security permissions, we have replaced the use of SA keys to workload identity providers. This change will also implement the use of environments to ensure deployments are going through the right channels.
=> Environment Lock

reanalysis/clinvar_runner.py, reanalysis/summarise_clinvar_entries.py, test/test_clinvar.py
- There is a bug [here](https://github.com/populationgenomics/automated-interpretation-pipeline/blob/4aa541f/reanalysis/summarise_clinvar_entries.py#L345) - if no filtering date is specified, this removes undated submissions. The correct action would be to only remove un-dated if a date filter is being applied
- The current version of the submission generation removes all entries with 'no assertion criteria provided', but in the AIP category logic we accommodate 0-star reviews. The current format cannot create 0-star clinvar ratings.
- The ClinvArbitration version was already patched to deal with ClinVar's weird approach to PAR regions - X and Y versions of the same variant share a single ID. This results in us dropping some chrX variants.
- Takes the latest version from …
=> ClinVar Re-processing Updates

reanalysis/models.py
- The Models used are defined in code, but on file as JSON. We currently have no way of determining whether the current code is correct to parse the model JSON
- adds a separate model version ID in the codebase (in models.py)
- adds this model version ID to the JSON objects written to file as a top-level attribute
- Future changes to the models can cause a change in version number, so reading an object from file becomes a multi-step process:
1. read the model version attr from the JSON data
2. if current != version in file, read as JSON, pass through an adapter method, then parse as a current object (e.g. adding in missing mandatory fields, or changing a string to a list of strings)
4. if current == version in file, parse JSON directly
This will be a starting point, and any breaking …
=> Adds versions to models

reanalysis/hpo_panel_match.py, reanalysis/models.py, reanalysis/templates/variant_table_child_row.html.jinja, test/test_metamist_hpo.py, test/test_validate_methods.py
- #378, but clean
- Currently we have `HPO - description` compound strings in the stored data, which causes issues when we want just HPO IDs downstream
- Implements a phenopacket entity structure: a dictionary of ID and LABEL
- all relevant test and model changes to accommodate that
- I've stacked a PR [here](https://github.com/populationgenomics/automated-interpretation-pipeline/pull/392) which would add model versioning (so model changes like this can be tracked, and the parsing changed to be backwards compatible)
=> Change HPO storage

reanalysis/html_builder.py
- The target cohort was almost entirely nnW, but a couple of nnG's snuck in, breaking the everything-is-a-date check
- allows for a generic pattern, [number, number, not-number]
=> Allow for nnW and nnG, and generic for future use

helpers/parse_amissense_into_ht.py, talos/vep_vcf_to_mt.py
- The TSV -> HT script I wrote works for the main-transcript only file, but the all-isoforms file contains an extra column
- adds a new method to detect the appropriate column to pull data from using the header line
- flexible for both input files without explicitly requiring a user choice
=> Process all AlphaMissense files

src/talos/HPOFlagging.py, src/talos/templates/variant_table.html.jinja
- some variants are identified as having a phenotype match, even though they have no matching phenotypes, leading to a weird display
- There was a little bug in the logic - if a test was being run, a phenotype match date was assigned, even if no matching terms were found
- only create the report hover-over if there are matching terms
- don't assign a phenotype match date unless a match was found
=> Fix for empty "Phenotype Match" tooltip

src/talos/GeneratePanelData.py, test/test_metamist_hpo.py
Closes #433 
- When fuzzy-matching between participant and panel HPO terms we search 3 levels apart in the HPO ontology tree. If no matches are found within that 3-level search, quit searching and move on to the next
- This 3-level search limit was never based in anything, and nothing has been done to validate that 3 is a good number
- Limiting the search to 3 tiers also implicitly requires a degree of coordination between recruiting sites and PanelApp curators, which we do not have in place. There's nothing to suggest that the data we process from participant cohorts and PanelApp have tuned matches to within 3 levels of HPO hierarchy, so it's likely we've been missing out on valid matches by cutting our searches short.
- Removes the max-level cap of 3 completely. The search now becomes …
=> Feature 433: Remove HPO tree limit

requirements.txt, src/talos/utils.py
- the backoff library doesn't work as expected - despite being configured (via the backoff decorator) to use a fibonacci backoff, expanding up to 200 seconds with each additional failure, it's really waiting only a fraction of a second between retries
- instead of continually attempting to get blood from this particular stone, moving on to a manual reimplementation
- removes the backoff library as a dependency and in code
- adds an exponential backoff retry, accepting a range of error modes
=> Manually implement request backoff/retry

requirements.txt, src/talos/RunHailFilteringSV.py
- We're missing some CNV calls due to whole sites being failed due to a failing Q score at any one component participant
- Scrap the Q score filter when processing SVs
- ... that's it
- CyVCF2 doesn't have a way to check out the Q scores on the VCFs coming out of SVAnnotate via Hail, so it's non-trivial to flag some of these Q failures later.
=> Trust SV qualities

src/talos/RunHailFiltering.py, src/talos/VcfToMt.py, src/talos/data_model.py, src/talos/example_config.toml
Really minor QOL change to make redeployment easier
- The artificial VCF generator, `data_model.py` currently generates variant data we can use in validation
- This VCF generator currently includes the `variant_class` attribute, and elsewhere in Talos we require this annotation
- This is an optional annotation from VEP, and we just pass it around, it's never used.
- Requiring presence of variant_class means that we fail if a useless field is absent in variant data
- Removes `variant_class` from everywhere
=> This PR removes the variant_class attribute

src/talos/CPG/MakePhenopackets.py, src/talos/GeneratePanelData.py, src/talos/HPOFlagging.py, src/talos/ValidateMOI.py, src/talos/models.py, src/talos/moi_tests.py, src/talos/templates/sample_index.html.jinja, src/talos/utils.py, test/test_moi_tests.py
- It's been noted that we occasionally let one variant of a comp-het pair slide off the report. This doesn't make sense, as a pairing between two variants should be symmetrical in terms of reaching the report.
- I originally assumed this was related to the report changes; we no longer create a 'latest-only' report, but when we did there was some logic around "keep all variants which were new in the latest round, and any variants they pair with"
- The real fault here was that the `check_frequency_passes` method (which permits/blocks variants based on gnomAD frequencies) was usually combined with an escape "always allow if pathogenic in ClinVar".
- This ClinVar escape only applied to the 'principal' variant in a pair, and not the partner:
```
Variant 1 is common, and pathogenic in ClinVar …
```
=> Fix comp het exclusion

requirements.txt, src/talos/FindGeneSymbolMap.py, src/talos/utils.py
- In FindGeneSymbolMap we sometimes hit errors which crash the process
- This has been tuned for us (Australia?) but the threshold for query frequency might be different elsewhere... using a backoff wrapper is a better approach than just experimenting with batch sizes until it stops breaking
- use the tenacity library to retry the queries
- replace the homebrewed retry/backoff wrapper with tenacity elsewhere as well
=> Use tenacity as a 3rd party retry wrapper

src/talos/SummariseReport.py
- The variant summary block is not accessible now that it's been dropped from the report
- Longer term view, this should land back in the reports properly. It's just not clear (to me) how to combine both the faster datatables and tabulated view
- Adds a slimmed-down version of [this](https://github.com/populationgenomics/talos/blob/main/src/talos/CreateTalosHTML.py#L252) to the JSON report printer
- This is the general vibe of the output based on the fake test data (nextflow demo files)
```json
{
"family_breakdown": {
"trios": 1,
"male": 2,
"affected": 1,
"female": 1
},
"variant_summary": {
"any": {
"Description": "All Variants",
"Total": 5,
"Unique": 1,
"Peak #/sample": 5,
"Mean/sample": 5.0
},
"1": {
"Description": "ClinVar Pathogenic",
"Total": 3,
"Unique": 1,
"Peak #/sample": 3, …
```
=> Improved report summary script

src/talos/RunHailFiltering.py, src/talos/example_config.toml, src/talos/models.py, test/test_hail_categories.py, test/test_hail_filters.py
This is the current state of Talos as-run in the latest validation benchmarks. This PR is being made to separate the current logic from the proposed frequency filters. Adding both in the same PR will get messy.
- The addition of Exomiser and SpliceVarDB categories were done quite heavy-handedly - they were given equal weighting to ClinVar (i.e. a variant was able to escape a range of quality/frequency filters on the basis of SVDB or Exomiser annotations). This has been revoked ⛔ They are still given the impact of a full category, but are not given the escalated priority of ClinVar
- The application of data from Clinvar, Exomiser, and SVDB during the Hail stage can be overwhelming for the VM being used. This improves performance by annotating with ClinVar, applying the coarse filters where …
=> Partial fix for variant inflation

nextflow/inputs/config.toml, src/talos/HPOFlagging.py, src/talos/QueryPanelapp.py, src/talos/RunHailFilteringSv.py, src/talos/ValidateMOI.py, src/talos/example_config.toml, src/talos/templates/variant_table_row.html.jinja, src/talos/utils.py
- We don't have a way to overrule PanelApp MOI (e.g. to use Talos in a more exploratory way, testing for new gene~disease associations)
- We don't have a way to use a non-PanelApp gene data source
- After all PanelApp data has been queried as normal, checks config to see if any additional gene data should be added (example section in example_config.toml)
- User must supply at least an ENSG ID with each manually applied gene, optionally a MOI, symbol, chromosome
- If the gene was already detected via PanelApp, the Custom gene panel is added 
- extra panel ID 0 associated with the gene, a marker to detect manually updated genes
- If the PanelApp MOI was different to the manually supplied one, overwrite it. 
- If the gene was not detected in PanelApp, add a new gene section
- By default, the …
=> Add custom Gene-MOI data

README.md, nextflow/modules/annotation/ReformatAnnotatedVcfIntoHailTable/main.nf, nextflow/modules/annotation/TransferAnnotationsToMatrixTable/main.nf
- since finishing the Talos-Prep workflow, MatrixTables are no longer compressed (there was no benefit)
- removes the .gz suffix from the expected output of ReformatAnnotatedVcfIntoHailTable
- uses the tar argument --remove-files to remove the need for a compress + delete as separate commands
=> Patch nf modules

.gitignore, nextflow/inputs/echtvar_config.json, src/talos/cpg_internal_scripts/MinimiseOutputForSeqr.py, src/talos/example_config.toml, src/talos/moi_tests.py, src/talos/templates/variant_table_child_row.html.jinja, test/test_moi_tests.py
- There were still a few instances of 'seqr_link' hanging around in the codebase, causing errors
- The example echtvar file was absent (excluded due to a .gitignore rule) - this caused a Docker build failure
=> Remove seqr link text

nextflow/modules/annotation/TransferAnnotationsToMatrixTable/main.nf
- Seen in slack https://centrepopgen.slack.com/archives/C08APN7GM7V/p1748990830714699
- changes the MT extraction method to a copy, matching other outputs - NextFlow _does_ handle a recursive copy by default, so changing this to copy evades permission issues seen previously.
=> Update NF module to COPY MT out

src/talos/RunHailFiltering.py, src/talos/RunHailFilteringSv.py, src/talos/example_config.toml
- Talos' de novo detection method has poor tolerance for spanning deletions, or any other scenarios which can result in an single-length AD (Allele Depth) array.
- Inserts a strict filter for spanning alleles, and a logging message to acknowledge their removal from the dataset 
- see https://gatk.broadinstitute.org/hc/en-us/articles/360035531912-Spanning-or-overlapping-deletions-allele
- If these sites are still problematic, complete avoidance of this process can be done through configurable skipping of the whole de novo category
=> Remove "*"-alleles from the dataset

src/talos/moi_tests.py
- If a parent is in the pedigree as a mother/father, but not as their own row, we try to retrieve their affected status during comp-het testing, and fail as a result
- Ideal fix is to have the pedigree file limited to members in the callset for clarity, but that's going to be addressed in an upcoming change.
- During Comp-Het test, we skip any participants which are missing from the pedigree
- No need to check for this in other places - the callsets are filtered down to samples in the pedigree (samples with a private row, not just referenced as a relative) so this is fairly safe.
=> Skip over parents without a row in the pedigree

src/talos/UnifiedPanelAppParser.py, src/talos/cpg_internal_scripts/cpg_flow_utils.py
- Re-adds the 'remove genes from analysis if they needed a phenotype match but were only on the mendeliome' behaviour
- Correction to a boolean condition I swear I tested, which governs which MTs are picked up when running LongRead analysis
=> Two quick fixes

docs/Configuration.md, src/talos/moi_tests.py
- Quick correction to a documentation typo
- Comp-Het method fails to evaluate [small x SV] pairs, due to strict requirement that variants be Het. If Het is opposite a Deletion event, the variant caller will likely detect the event as a Hom instead
- Typo updated, min suggested GQ applied to all samples is 15 not 5
- MOI test method updated, we initially consider all Het and Hom variants, then pare back to Hom X Deletion compound events. This should detect real events without over-detecting multiple Hom-Hom pairs, as could be expected in large Deletions.
=> Doc bump, consider homs for CH test (SV)

README.md, nextflow/modules/annotation/FilterVcfToBedWithBcftools/main.nf, nextflow/modules/annotation/MergeVcfsWithBcftools/main.nf
- When data is provided directly using the `--merged_vcf` route, we didn't insert `AC/AF/AN` values in the INFO field
- We would expect most variant callers to populate these fields, but they're not mandatory, so this probably isn't a wise assumption to make
- Since inserting a fail-early module in the Talos workflow to ensure all required fields are present, this now causes the pipeline to fail for users who took the pre-merged path, but didn't have `INFO.AC/AF/AN` populated. 
- For the `merged_vcf` route we insert AC/AF/AN values when filtering down to a pre-defined BED region, README updated to explain this
- In future if users want an alternative source of AC/AN/AF or to use pre-embedded values, we can discuss how to do that
=> Insert AC/AF/AN attributes in the pre-merged VCF path

nextflow/modules/annotation/AnnotateCsqWithBcftools/main.nf, src/talos/cpg_internal_scripts/talos_stages.py
Adding a `--no-version` command to bcftools index isn't valid, remove that
Mito VCF detection needs a tweak
=> Remove —no-version from annotateCSQ
