.markdownlint.json, .pre-commit-config.yaml, .pylintrc, reanalysis/annotation.py, reanalysis/interpretation_runner.py, reanalysis/validate_categories.py, reanalysis/vep/jobs.py, requirements.txt, test/test_moi_tests.py
Addressing changes here: https://github.com/populationgenomics/cpg-utils/pull/46
Specifically, `image_path` and `reference_path` function now take the key in a global config, not suffix.
=> `image_path` and `reference_path` take key in config not suffix

reanalysis/comparison.py, test/conftest.py, test/test_aip_comparison.py
- Contributes to #19
- Adds a method for finding a variant in the Matrix Table
=> AIP part 6 - variant query in MT

reanalysis/html_builder.py, reanalysis/reanalysis_conf.json, test/test_html_builder.py
- closes #65
- closes #66 
- Better use of templating throughout
- Requirement that a variant have transcript consequences is removed
- If a sample has a Seqr family and an External ID, the section title is updated to be a hyperlink to the seqr family page
=> Html fixes

reanalysis/html_builder.py
- N/A
- makes all configuration-specified files properly optional
- `check_good_value` rejects missing keys and empty strings
=> actually optional arguments in config

comparison/comparison_wrapper.py, reanalysis/annotation.py, reanalysis/interpretation_runner.py, reanalysis/vep/jobs.py, requirements.txt, setup.py
* Remove old `hail_billing_project` and `hail_bucket` parameters to `query_function` (now read from CPG_CONFIG_PATH)
* CPG_DRIVER_IMAGE is not used and delegated to the toml config as well
* Annotation: skip adding rg37_locus (not doing anything, doing it properly is not supported by batch backend)
=> Adjustments for cpg_utils TOML configuration

release_scripts/validation_release.sh
- closes #101 
- adds a release script for the validation cohort data
=> add release script

reanalysis/hail_filter_and_label.py, reanalysis/mt_to_vcf.py
- issues stemming from #113 
- fixes the earlier header file commit 
- this is also fixed in the #108 #111 #112 #115 PR cascade, but this is being fast-tracked separately so that the MSFT deployment isn't broken
=> adds fixes from 113 independent of panel feature

release_scripts/csiro_release.sh
- closes https://github.com/populationgenomics/seqr-private/issues/11
- this script was added previously, but it was deleted by a messy rebase before it was run
=> re-add CSIRO release

helpers/pedigree_from_sample_metadata.py, reanalysis/query_panelapp.py
- I broke it
- dumb code change meant that the panelapp query only runs if the whole package is installed
- rather than install the package for a really quick script to run, just removing the dependency by copying the methods
=> accidentally broke it

reanalysis/html_builder.py
- Closes #162
- link out to the gene-specific panelapp page, not the gene-in-panel page (slow)
- see related issue for details
=> link out to gene-page

reanalysis/mt_to_vcf.py
- #159 
- If AC is an int, make it into a list when writing the AC value to VCF
- This is a fix outside of cpg_workflows
This has been solved in cpg_workflows as well, but this shouldn't clash, so no harm adopting both changes
=> update fields on MT to VCF write

reanalysis/validate_categories.py
=> remove double indexing bug

reanalysis/utils.py, reanalysis/validate_categories.py, test/test_results_comparison.py
- 🤯 
- in a previous PR I identified the MOI issue... then didn't fix it at all. I must have a rogue local commit I hadn't pushed which actually contains the fix
- also fixes the cumulative data filtering method to use the new results format (splitting sample metadata from sample variants)
=> Fix incremental data

.github/workflows/lint.yaml, .github/workflows/test.yaml
- N/A
- uses cache'ing in the CI builds
=> Build with cache

reanalysis/validate_categories.py
- Forgot to account for the presence of UNKNOWN status in the Pedigree - causes the JSON serialisation to fail
=> account for UNKNOWN in pedigree

reanalysis/summarise_clinvar_entries.py
- N/A
- reflecting the new field names in the Clinvar table - I had edited the intermediate JSON fields, but not the schema as parsed by Hail, leading to a decoding error.
- I'm a big derp, derpy derpy derp
=> Clinvar Table schema correction

release_scripts/broad_rgp_release.sh
- The last command was wrong
- The new command is right
=> release command correction

reanalysis/html_builder.py
- I left a silly print statement in the HTML printer
=> remove silly print statement

helpers/prepare_aip_cohort.py, reanalysis/utils.py
- The Helper script for cohort setup was not using the cohort section of the config
- Helper uses the cohort section of config to determine % of cohort to retain
- docstring tidy-up
=> 1.0.0 bugfixes

.github/workflows/index_page_builder.yaml
=> id-token permission

helpers/forbidden_gene_check.py, reanalysis/html_builder.py
- table/HTML generation fails if there are no cohort-forced panels
=> tables fail to generate if there are no 'forced panels'

reanalysis/templates/index.html.jinja
Same as prev., but this has actually been tested locally :D
=> still failing, but now it's fixed

reanalysis/clinvar_runner.py
- date option was not passed in the clinvar wrapper
- previous change somehow turned a TV on, this will rectify that mistake
- ... passes a date argument, if supplied
- turns off the TV
=> pass date to clinvar summariser

.github/workflows/index_page_builder.yaml
- ID Token for report collation action
-
-
-
=> Use audience + impersonate for id-token

.github/workflows/index_page_builder.yaml
Required to write HTML into test
=> standard -> full job permissions

design_docs/Hail_Filter_and_Label.md, design_docs/Helpers.md, design_docs/MOI_Checks.md, design_docs/PanelApp_interaction.md, design_docs/annotation_source.md, helpers/prepare_aip_cohort.py, reanalysis/reanalysis_global.toml
- N/A
- adds documentation of new features
- re-writes outdated chunks of documentation
- documents the information source for each filter and category
=> Documentation updates

reanalysis/reanalysis_global.toml
Set default panesls for all disease specific projects.
=> Add panel defaults

reanalysis/interpretation_runner.py, reanalysis/reanalysis_global.toml
- Introduced a bug where the storage/memory request defaults are suffixed "GiB", where only `G` or `Gi` would be permitted
- `GiB` -> `Gi`
=> Storage fits regex

.github/workflows/clinvar_runner.yaml, reanalysis/clinvar_runner.py, reanalysis/summarise_clinvar_entries.py
Can you pls check if this would be the right way to send extra config params via a curl?
failing batch as reference
https://batch.hail.populationgenomics.org.au/batches/424192/jobs/1
=> updated clinvar workflow

reanalysis/clinvar_runner.py, requirements.txt
- closes #297
- logic was inaccurate; this splits up the check for new and previous jobs
=> dag correction

release_scripts/csiro_release.sh
- Closes #300
- Script for copying ClinVar data in VCF & Table form to the Acute-Care release bucket
-
-
=> Release Clinvar data

reanalysis/moi_tests.py, reanalysis/utils.py, reanalysis/validate_categories.py, test/test_moi_tests.py, test/test_utils.py
- Some stupid code
- Previously I was taking the AbstractVariant model and stripping out some useless data so that the summary result JSON wasn't too large
- This was done in a dumb way, removing a bunch of model attributes
- This uses an alternative approach - instead of minimising by removing random pieces of the model, the MinimalVariant object is created for consistency
- MinimalVariant is a subset of the AbstractVariant Class, and resembles the actual thing I was bodging before
=> Use minimised representation

helpers/prepare_aip_cohort.py, reanalysis/interpretation_runner.py
- Arguments for the AIP worker modules changed during pipeline adaptation
- Changes the input flags to the format expected
- Secondary change to how the Pedigree files are built when running Singleton analysis
=> Updates module arguments

reanalysis/hail_filter_sv.py, reanalysis/html_builder.py, reanalysis/moi_tests.py, reanalysis/templates/variant_table.html.jinja, reanalysis/utils.py
- Closes #206
- If sample/family is absent from Seqr, don't generate any Seqr hyperlinks
=> Only generate hyperlinks for seqr families

reanalysis/interpretation_runner.py
=> Passes the wrong MT to SV labelling

reanalysis/minimise_output_for_seqr.py
- Currently we pass one path, write a file to that path, then maybe write a second file to a modified version of that path
- in hindsight, a stupid idea
- This means that the pipeline-run version of AIP is generating both files, but doesn't know to copy the second file out of the job, so we're not generating phenotype-specific seqr files
- adds two CLI arguments, one for each file
=> Writes pheno-specific output to a provided path

Dockerfile
- [< the issue solved by this PR >](https://centrepopgen.slack.com/archives/C018KFBCR1C/p1710895635573669)
=> Revert base image

src/talos/templates/sample_index.html.jinja
This is just the branch from #448 with a valid branch name for building the package directly in our images repo
=> Correct number of cols in  sample report

.github/workflows/security-checks.yaml
Adds pip-audit to scan all the packages from your requirements, for any known vulnerabilities in the Python Packaging Advisory Database.
=> Create security-checks.yaml for pip-audit

src/talos/liftover/lift_1_0_3_to_1_1_0.py, src/talos/scripts/metadata_from_json.py
- Sometimes we'd like to get a quick cohort overview from an old analysis
=> Print metadata from report json

src/talos/SummariseReport.py
completely irrelevant to the other PR, but
=> Alter prefix grouping

src/talos/RunHailFiltering.py, src/talos/example_config.toml
- Made de novo parameters configurable
- Deletes the method which shoved artificial AD values into the genotype calls
-
-
-
=> Reinvented de novo calling side branch

README.md, nextflow/modules/talos/RunHailFiltering/main.nf, nextflow/talos.nf
No functional change, just updating README + wiring.
=> Update config as cohort input MTs aren't tar'd up anymore

src/talos/RunHailFiltering.py
- Bug introduced yesterday - I was running the tests locally and spotted this failure, but the same tests ran just fine in the CI workflow, so the PR was already merged
=> Correct bug in RunHailFiltering

src/talos/ValidateMOI.py, src/talos/models.py
- Extended correction for 'unknown' sex lookup when generating family structures & stats
=> Male female fix

src/talos/RunHailFiltering.py
- Previous attempt at this change made this fix forgot to reassign the value after 😢
=> Correction to de novo dodge [BCH]

src/talos/utils.py
=> Fail gracefully if history folder contains invalid file names

CHANGELOG.md, large_files/gather_file.sh, nextflow/annotation.config
- New Ensembl GFF available, not an essential update
- bumps the targeted version in the config & downloader script
- Changelog updated to reflect the TxCSQ change and this
-
- [-] Version Bumped
=> Update ensembl GFF3 to 115
